
server:
  port: 8080

spring:
  application:
    name: graph-routes-api

  neo4j:
    uri: ${SPRING_NEO4J_URI:${NEO4J_URI:}}
    authentication:
      username: ${SPRING_NEO4J_AUTHENTICATION_USERNAME:${NEO4J_USER:neo4j}}
      password: ${SPRING_NEO4J_AUTHENTICATION_PASSWORD:${NEO4J_PASS:neo4j}}
    security:
      encrypted: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
